import './components/menu';
import './components/scroll';
import './components/tabs';
import './components/accordion';
import './components/modals';
import './components/sliders';
import './components/fslightbox';
// import './components/validate-forms';
import './components/fullpage-scroll';
// import './components/fix-full-height';
