import './components/menu';
import './components/scroll';
import './components/tabs';
import './components/accordion';
import './components/modals';
import './components/sliders';
import './components/fslightbox';
import './components/validation';
import './components/fullpage-scroll';
import './components/animations';
// import './components/fix-full-height';
