import './components/menu';
import './components/scrollbar';
import './components/tabs';
import './components/modals';
import './components/sliders';
import './components/fslightbox';
import './components/validation';
import './components/fullpage-scroll';
import './components/animations';
